apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: "org.jlleitschuh.gradle.ktlint"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'
apply from: '../versioning.gradle'

def appVersionName = "v1.0.22"

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.voizy.android"
        minSdkVersion 24
        targetSdkVersion 28
        versionName appVersionName
        versionCode buildVersionCode(appVersionName)
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
            versionNameSuffix = '-debug'
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "env"

    productFlavors {
        envPro {
            dimension "env"
        }
        envOldPro {
            dimension "env"
        }
        envDev {
            dimension "env"
        }
    }

    ktlint {
        ignoreFailures = false
    }
    preBuild.dependsOn(ktlintCheck)

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
        kotlinOptions {
            jvmTarget = '1.8'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
    implementation "org.koin:koin-android:$koin_version"
    implementation "org.koin:koin-core:$koin_version"
    implementation "org.koin:koin-androidx-viewmodel:$koin_version"
    implementation 'com.jakewharton.timber:timber:4.7.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.15'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation "androidx.paging:paging-runtime:$paging_version"
    implementation "androidx.paging:paging-rxjava2:$paging_version"

    implementation "com.uber.autodispose:autodispose:$auto_dispose_version"
    implementation "com.uber.autodispose:autodispose-lifecycle:$auto_dispose_version"
    implementation "com.uber.autodispose:autodispose-android-archcomponents:$auto_dispose_version"
    implementation "com.uber.autodispose:autodispose-android:$auto_dispose_version"
    implementation "com.uber.autodispose:autodispose-rxlifecycle:$auto_dispose_version"

    implementation 'com.jakewharton.rxbinding2:rxbinding:2.0.0'

    implementation 'com.google.firebase:firebase-firestore:21.3.0'
    implementation 'com.google.firebase:firebase-storage:19.1.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.1'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    implementation 'com.arthenica:mobile-ffmpeg-full:4.3'

    implementation 'com.github.yausername.youtubedl-android:library:0.7.+'

    testImplementation "androidx.paging:paging-common:$paging_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
